theme: jekyll-theme-cayman

#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Variables ID

# Short bio or description (displayed in the header)
description: A place to play codes

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars3.githubusercontent.com/u/39725238?s=400&u=a2ff4a191e74b632ff8f821e505a82c463f15e24&v=4

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: variables.team@gmail.com
  facebook:
  flickr:
  github: variablesid/variablesid.github.io
